Repository npgsql/npgsql, pull requests merged in 2018-09, with the labels that each got.

#2137 Expose `DefaultNameTranslator` on `INpgsqlTypeMapper`
  src/Npgsql/TypeMapping/ConnectorTypeMapper.cs
  src/Npgsql/TypeMapping/GlobalTypeMapper.cs
  src/Npgsql/TypeMapping/INpgsqlTypeMapper.cs
  src/Npgsql/TypeMapping/TypeMapperBase.cs
Labels: enhancement

#2139 Expose `DefaultNameTranslator` on `INpgsqlTypeMapper`
  src/Npgsql/TypeMapping/ConnectorTypeMapper.cs
  src/Npgsql/TypeMapping/GlobalTypeMapper.cs
  src/Npgsql/TypeMapping/INpgsqlTypeMapper.cs
  src/Npgsql/TypeMapping/TypeMapperBase.cs
Labels: enhancement

#2149 Fixed boxing in generic write method for arrays
  src/Npgsql/TypeHandlers/ArrayHandler.cs
Labels: performance

#2164 Added missing `)` in doc/types/jsonnet.md
  doc/types/jsonnet.md
Labels: doc

#2167 Fixed mistakes in enum and composites docs
  doc/types/enums_and_composites.md
Labels: doc
