Repository npgsql/npgsql, pull requests merged in 2019-09, with the labels that each got.

#2599 Minor cleanup all around
  .editorconfig
  Npgsql.sln.DotSettings
  src/Npgsql.GeoJSON/NpgsqlGeoJSONExtensions.cs
  src/Npgsql.Json.NET/JsonHandler.cs
  src/Npgsql.Json.NET/JsonbHandler.cs
  src/Npgsql.NetTopologySuite/NetTopologySuiteHandler.cs
  src/Npgsql.NetTopologySuite/NpgsqlNetTopologySuiteExtensions.cs
  src/Npgsql.RawPostgis/NpgsqlRawPostgisExtensions.cs
  src/Npgsql.RawPostgis/PostgisRawHandler.cs
  src/Npgsql/BackendMessages/AuthenticationMessages.cs
  src/Npgsql/BackendMessages/RowDescriptionMessage.cs
  src/Npgsql/Common.cs
  src/Npgsql/Counters.cs
  src/Npgsql/Logging/NpgsqlLogManager.cs
  src/Npgsql/NpgsqlBinaryExporter.cs
  src/Npgsql/NpgsqlBinaryImporter.cs
  src/Npgsql/NpgsqlCommand.cs
  src/Npgsql/NpgsqlConnector.Auth.cs
  src/Npgsql/NpgsqlConnector.cs
  src/Npgsql/NpgsqlDataReader.cs
  src/Npgsql/NpgsqlDatabaseInfo.cs
  src/Npgsql/NpgsqlLargeObjectManager.cs
  src/Npgsql/NpgsqlLargeObjectStream.cs
  src/Npgsql/NpgsqlParameter.cs
  src/Npgsql/NpgsqlParameter`.cs
  src/Npgsql/NpgsqlReadBuffer.Stream.cs
  src/Npgsql/NpgsqlSchema.cs
  src/Npgsql/NpgsqlTransaction.cs
  src/Npgsql/NpgsqlTypes/NpgsqlTimeSpan.cs
  src/Npgsql/NpgsqlTypes/NpgsqlTsVector.cs
  src/Npgsql/NpgsqlTypes/NpgsqlTypes.cs
  src/Npgsql/NpgsqlTypes/NpgsqlUserTypes.cs
  src/Npgsql/NpgsqlWriteBuffer.Stream.cs
  src/Npgsql/PoolManager.cs
  src/Npgsql/PostgresMinimalDatabaseInfo.cs
  src/Npgsql/PregeneratedMessages.cs
  src/Npgsql/SqlQueryParser.cs
  src/Npgsql/TypeHandlers/ArrayHandler.cs
  src/Npgsql/TypeHandlers/BitStringHandler.cs
  src/Npgsql/TypeHandlers/JsonHandler.cs
  src/Npgsql/TypeHandlers/NumericHandlers/MoneyHandler.cs
  src/Npgsql/TypeHandlers/TextHandler.cs
  src/Npgsql/TypeHandlers/UnmappedEnumHandler.cs
  src/Npgsql/TypeHandling/NpgsqlSimpleTypeHandler.cs
  src/Npgsql/TypeHandling/NpgsqlTypeHandler`.cs
  src/Npgsql/TypeMapping/ConnectorTypeMapper.cs
  src/Npgsql/TypeMapping/EntityFrameworkCoreCompat.cs
  src/Npgsql/TypeMapping/TypeMapperBase.cs
  src/Npgsql/Util/CodeAnalysis.cs
  src/Npgsql/Util/DbDataReaderExtensions.cs
  src/Npgsql/Util/VersionExtensions.cs
  src/Npgsql/VolatileResourceManager.cs
  src/Npgsql/WindowsUsernameProvider.cs
Labels: refactor

#2602 Use switch expressions
  src/Npgsql.GeoJSON/GeoJSONHandler.cs
  src/Npgsql/BackendMessages/CopyMessages.cs
  src/Npgsql/NpgsqlCommand.cs
  src/Npgsql/NpgsqlConnection.cs
  src/Npgsql/NpgsqlConnector.cs
  src/Npgsql/NpgsqlDataReader.cs
  src/Npgsql/NpgsqlSchema.cs
  src/Npgsql/NpgsqlTypes/NpgsqlDate.cs
  src/Npgsql/NpgsqlTypes/NpgsqlDateTime.cs
  src/Npgsql/NpgsqlTypes/NpgsqlTsQuery.cs
  src/Npgsql/NpgsqlTypes/NpgsqlTypes.cs
  src/Npgsql/PostgresTypes/PostgresBaseType.cs
  src/Npgsql/Schema/DbColumn.cs
  src/Npgsql/Schema/NpgsqlDbColumn.cs
  src/Npgsql/TypeHandlers/CompositeHandlers/CompositeHandler.cs
  src/Npgsql/TypeHandlers/DateTimeHandlers/DateHandler.cs
  src/Npgsql/TypeHandlers/FullTextSearchHandlers/TsQueryHandler.cs
  src/Npgsql/TypeHandlers/GeometricHandlers/PathHandler.cs
  src/Npgsql/TypeHandlers/NetworkHandlers/InetHandler.cs
  src/Npgsql/VolatileResourceManager.cs
  test/Npgsql.Tests/ReaderOldSchemaTests.cs
  test/Npgsql.Tests/Support/NLogLoggingProvider.cs
  test/Npgsql.Tests/Types/NumericTypeTests.cs
Labels: refactor

#2605 Simplified usings in the source
  src/Npgsql/NpgsqlCommand.cs
  src/Npgsql/NpgsqlConnector.Auth.cs
  src/Npgsql/NpgsqlLargeObjectManager.cs
  src/Npgsql/NpgsqlSchema.cs
  src/Npgsql/PostgresDatabaseInfo.cs
  src/Npgsql/Schema/DbColumnSchemaGenerator.cs
  src/Npgsql/VolatileResourceManager.cs
  src/Npgsql/WindowsUsernameProvider.cs
Labels: refactor

#2619 Changed exporter to follow the coding style
  src/Npgsql/NpgsqlBinaryExporter.cs
  src/Npgsql/NpgsqlConnector.cs
Labels: refactor

#2611 make package and project site urls use https
  Directory.Build.props
  README.md
  doc/release-notes/3.0.md
  src/Npgsql/NpgsqlConnectionStringBuilder.cs
  src/VSIX/source.extension.vsixmanifest
Labels: documentation

#2633 Icon embedded into the NuGet package
  Directory.Build.props
  postgresql.png
Labels: infrastructure

#2637 Updated PostGIS
  .appveyor.yml
Labels: infrastructure

#2523 Added reading support of immutable composites
  src/Npgsql/NpgsqlTypes/NpgsqlUserTypes.cs
  src/Npgsql/TypeHandlers/CompositeHandlers/CompositeConstructorHandler.cs
  src/Npgsql/TypeHandlers/CompositeHandlers/CompositeConstructorHandler`.cs
  src/Npgsql/TypeHandlers/CompositeHandlers/CompositeHandler.cs
  src/Npgsql/TypeHandlers/CompositeHandlers/CompositeParameterHandler.cs
  src/Npgsql/TypeHandlers/CompositeHandlers/CompositeParameterHandler`.cs
  src/Npgsql/TypeHandlers/CompositeHandlers/CompositeTypeHandlerFactory.cs
  src/Npgsql/TypeMapping/INpgsqlTypeMapper.cs
  src/Npgsql/TypeMapping/TypeMapperBase.cs
  test/Npgsql.Tests/Types/CompositeHandlerTests.Read.cs
  test/Npgsql.Tests/Types/CompositeHandlerTests.Write.cs
  test/Npgsql.Tests/Types/CompositeHandlerTests.cs
Labels: enhancement

#2659 Removed Travis CI related things
  README.md
  test/Npgsql.Tests/ConnectionTests.cs
Labels: documentation, test
