Repository npgsql/npgsql, pull requests merged in 2019-02, with the labels that each got.

#2310 Remove unsafe code from UuidHandler
  src/Npgsql/TypeHandlers/UuidHandler.cs
Labels: performance

#2315 Added solution wide Directory.Build.props
  Directory.Build.props
  src/Directory.Build.props
  src/Npgsql.GeoJSON/Npgsql.GeoJSON.csproj
  src/Npgsql.Json.NET/Npgsql.Json.NET.csproj
  src/Npgsql.LegacyPostgis/Npgsql.LegacyPostgis.csproj
  src/Npgsql.NetTopologySuite/Npgsql.NetTopologySuite.csproj
  src/Npgsql.NodaTime/Npgsql.NodaTime.csproj
  src/Npgsql.RawPostgis/Npgsql.RawPostgis.csproj
  src/Npgsql/Npgsql.csproj
  test/Directory.Build.props
  test/Npgsql.Benchmarks/Npgsql.Benchmarks.csproj
  test/Npgsql.PluginTests/Npgsql.PluginTests.csproj
  test/Npgsql.Tests/Npgsql.Tests.csproj
Labels: refactor

#2322 Removed default build properties
  Directory.Build.props
Labels: refactor

#2344 Use BinaryPrimitives to leverage JIT intrinsics
  src/Npgsql/NpgsqlReadBuffer.cs
  src/Npgsql/NpgsqlWriteBuffer.cs
  src/Npgsql/PGUtil.cs
Labels: enhancement
