Repository npgsql/npgsql, pull requests merged in 2019-08, with the labels that each got.

#2558 Fixed handling of array segments without arrays
  src/Npgsql/TypeHandlers/ByteaHandler.cs
  src/Npgsql/TypeHandlers/TextHandler.cs
Labels: bug

#2569 Optimized type loading
  src/Npgsql/PostgresDatabaseInfo.cs
  src/Npgsql/Util/DbDataReaderExtensions.cs
Labels: enhancement

#2585 Tighten nullability annotations in type handling
  src/Npgsql.Json.NET/JsonHandler.cs
  src/Npgsql.Json.NET/JsonbHandler.cs
  src/Npgsql/TypeHandlers/ArrayHandler.cs
  src/Npgsql/TypeHandlers/JsonHandlers.cs
  src/Npgsql/TypeHandlers/NetworkHandlers/InetHandler.cs
  src/Npgsql/TypeHandlers/RangeHandler.cs
  src/Npgsql/TypeHandlers/UnknownTypeHandler.cs
  src/Npgsql/TypeHandlers/UnmappedEnumHandler.cs
  src/Npgsql/TypeHandling/NpgsqlSimpleTypeHandler.cs
  src/Npgsql/TypeHandling/NpgsqlTypeHandler.cs
  src/Npgsql/TypeHandling/NpgsqlTypeHandler`.cs
Labels: enhancement

#2581 Added provider specific ExecuteReaderAsync methods
  src/Npgsql/NpgsqlCommand.cs
  src/Npgsql/PostgresDatabaseInfo.cs
Labels: enhancement

#2519 Pool contention enhancements and bug fixes
  src/Npgsql/ConnectorPool.cs
  src/Npgsql/NpgsqlConnection.cs
  src/Npgsql/NpgsqlConnector.cs
  src/Npgsql/NpgsqlEventSource.cs
  test/Npgsql.Tests/PoolManagerTests.cs
  test/Npgsql.Tests/PoolTests.cs
Labels: performance
