Repository npgsql/npgsql, pull requests merged in 2019-10, with the labels that each got.

#2672 Support the new snupkg format
  src/Directory.Build.props
Labels: infrastructure

#2685 Moved out test util class from the driver
  src/Npgsql/Util/PGUtil.cs
  test/Npgsql.Tests/TestUtil.cs
  test/Npgsql.Tests/Types/NumericTypeTests.cs
  test/Npgsql.Tests/TypesTests.cs
Labels: test

#2671 Update project url
  Directory.Build.props
Labels: infrastructure

#2697 Decreased memory usage in name translator
  src/Npgsql/NameTranslation/NpgsqlSnakeCaseNameTranslator.cs
Labels: enhancement

#2704 Add unit of measure and default to ConnectionTimeout
  src/Npgsql/NpgsqlCommand.cs
  src/Npgsql/NpgsqlConnection.cs
Labels: enhancement

#2693 Use in modifier
  src/Npgsql.GeoJSON/CrsMap.cs
  src/Npgsql/NpgsqlTypes/NpgsqlDate.cs
  src/Npgsql/NpgsqlTypes/NpgsqlDateTime.cs
  src/Npgsql/NpgsqlTypes/NpgsqlTimeSpan.cs
Labels: enhancement
