Repository npgsql/npgsql, pull requests merged in 2019-03, with the labels that each got.

#2346 Cleaned up PostgresException
  src/Npgsql/PostgresException.cs
  test/Npgsql.Tests/ExceptionTests.cs
Labels: breakage, enhancement

#2354 Remove deprecated floating-point date/time format
  src/Npgsql.NodaTime/IntervalHandler.cs
  src/Npgsql.NodaTime/TimeHandler.cs
  src/Npgsql.NodaTime/TimeTzHandler.cs
  src/Npgsql.NodaTime/TimestampHandler.cs
  src/Npgsql.NodaTime/TimestampTzHandler.cs
  src/Npgsql/TypeHandlers/DateTimeHandlers/IntervalHandler.cs
  src/Npgsql/TypeHandlers/DateTimeHandlers/TimeHandler.cs
  src/Npgsql/TypeHandlers/DateTimeHandlers/TimeTzHandler.cs
  src/Npgsql/TypeHandlers/DateTimeHandlers/TimestampHandler.cs
  src/Npgsql/TypeHandlers/DateTimeHandlers/TimestampTzHandler.cs
Labels: breakage

#2362 Fixes of wrong priority of operator "??"
  src/Npgsql/FrontendMessages/PasswordMessage.cs
  src/Npgsql/NpgsqlTypes/NpgsqlRange.cs
  src/Npgsql/PostgresTypes/PostgresFacets.cs
Labels: bug

#2370 Use Span for Substring in Netstandard 2.1+
  src/Npgsql/SqlQueryParser.cs
  src/Npgsql/Util/StringBuilderExtensions.cs
Labels: performance

#2385 Change minimum supported .NET Framework from 4.5.2 to 4.6.1
  .appveyor.yml
  src/Directory.Build.props
  src/MSI/MSI.wixproj
  src/MSI/Npgsql.wxs
  src/Npgsql.NetTopologySuite/NetTopologySuiteHandler.cs
  src/Npgsql/Common.cs
  src/Npgsql/ConnectorPool.cs
  src/Npgsql/Counters.cs
  src/Npgsql/Npgsql.csproj
  src/Npgsql/NpgsqlCommand.cs
  src/Npgsql/NpgsqlConnection.cs
  src/Npgsql/NpgsqlConnector.cs
  src/Npgsql/NpgsqlDataReader.cs
  src/Npgsql/NpgsqlReadBuffer.Stream.cs
  src/Npgsql/NpgsqlReadBuffer.cs
  src/Npgsql/NpgsqlWriteBuffer.Stream.cs
  src/Npgsql/NpgsqlWriteBuffer.cs
  src/Npgsql/PGUtil.cs
  src/Npgsql/Schema/DbColumn.cs
  src/Npgsql/TypeHandlers/ArrayHandler.cs
  src/Npgsql/TypeHandlers/RangeHandler.cs
  src/Npgsql/TypeHandling/NpgsqlSimpleTypeHandler.cs
  src/Npgsql/TypeHandling/NpgsqlTypeHandler`.cs
  src/Npgsql/Util/StringBuilderExtensions.cs
  src/Npgsql/WindowsUsernameProvider.cs
  src/VSIX/VSIX.csproj
  test/Directory.Build.props
  test/Npgsql.Benchmarks/Npgsql.Benchmarks.csproj
  test/Npgsql.PluginTests/Support/DebugAssertSetupFixture.cs
  test/Npgsql.Tests/ConnectionTests.cs
  test/Npgsql.Tests/DistributedTransactionTests.cs
  test/Npgsql.Tests/Npgsql.Tests.csproj
  test/Npgsql.Tests/PerformanceCounterTests.cs
  test/Npgsql.Tests/Support/DebugAssertSetupFixture.cs
  test/Npgsql.Tests/TestUtil.cs
Labels: breakage

#2398 Guard against NRE during broken COPY cleanup
  src/Npgsql/NpgsqlBinaryExporter.cs
  src/Npgsql/NpgsqlBinaryImporter.cs
  test/Npgsql.Tests/CopyTests.cs
Labels: bug

#2407 Backport: Guard against NRE during broken COPY cleanup
  src/Npgsql/NpgsqlBinaryExporter.cs
  src/Npgsql/NpgsqlBinaryImporter.cs
  test/Npgsql.Tests/CopyTests.cs
Labels: bug
