Repository npgsql/npgsql, pull requests merged in 2019-04, with the labels that each got.

#2382 Recycle RowDescription and FieldDescription
  src/Npgsql/BackendMessages/RowDescriptionMessage.cs
  src/Npgsql/NpgsqlCommand.cs
  src/Npgsql/NpgsqlConnector.cs
Labels: performance

#2414 Added asynchronous transaction savepoint functions.
  src/Npgsql/NpgsqlTransaction.cs
  test/Npgsql.Tests/TransactionTests.cs
Labels: enhancement

#2401 Cache the value of data source property
  src/Npgsql/NpgsqlConnection.cs
  src/Npgsql/NpgsqlConnectionStringBuilder.cs
  test/Npgsql.Tests/ConnectionTests.cs
Labels: performance

#2420 Fix NoTypeLoading compatibility mode
  src/Npgsql/PostgresMinimalDatabaseInfo.cs
  test/Npgsql.Tests/ConnectionTests.cs
Labels: bug

#2421 Small SQL parser refactor around conformant strings
  src/Npgsql/NpgsqlCommand.cs
  src/Npgsql/NpgsqlConnector.cs
  src/Npgsql/SqlQueryParser.cs
  test/Npgsql.Tests/SqlQueryParserTests.cs
Labels: refactor
