Repository npgsql/npgsql, pull requests merged in 2019-07, with the labels that each got.

#2508 Fixes potential PoolState.Waiting overflow and includes some minor changes
  src/Npgsql/ConnectorPool.cs
  test/Npgsql.Tests/PoolTests.cs
Labels: enhancement

#2524 doc fix: VSIX for VS2019 support
  doc/ddex.md
Labels: documentation

#2530 Removed conditional compilation block for Silverlight
  src/Npgsql/Logging/NpgsqlLogManager.cs
Labels: refactor

#2528 Align versions for CI artifact consistency
  .appveyor.yml
  .build/setup_appveyor.ps1
  Directory.Build.props
  src/Npgsql.GeoJSON/Npgsql.GeoJSON.csproj
  src/Npgsql.Json.NET/Npgsql.Json.NET.csproj
  src/Npgsql.LegacyPostgis/Npgsql.LegacyPostgis.csproj
  src/Npgsql.NetTopologySuite/Npgsql.NetTopologySuite.csproj
  src/Npgsql.NodaTime/Npgsql.NodaTime.csproj
  src/Npgsql.RawPostgis/Npgsql.RawPostgis.csproj
  src/Npgsql/Npgsql.csproj
  src/VSIX/Properties/AssemblyInfo.cs
  src/VSIX/source.extension.vsixmanifest
Labels: infrastructure, refactor

#2544 Bump version to 4.0.9 and move it to Directory.Build.props
  .appveyor.yml
  bump.sh
  src/Directory.Build.props
  src/Npgsql.GeoJSON/Npgsql.GeoJSON.csproj
  src/Npgsql.Json.NET/Npgsql.Json.NET.csproj
  src/Npgsql.LegacyPostgis/Npgsql.LegacyPostgis.csproj
  src/Npgsql.NetTopologySuite/Npgsql.NetTopologySuite.csproj
  src/Npgsql.NodaTime/Npgsql.NodaTime.csproj
  src/Npgsql.RawPostgis/Npgsql.RawPostgis.csproj
  src/Npgsql/Npgsql.csproj
  src/VSIX/Properties/AssemblyInfo.cs
  src/VSIX/source.extension.vsixmanifest
Labels: infrastructure

#2547 Catch another localtime exception
  src/Npgsql.NodaTime/TimestampTzHandler.cs
Labels: bug

#2545 Fixed bump.sh to update version in common props
  bump.sh
Labels: infrastructure
