Repository npgsql/npgsql, pull requests merged in 2020-10, with the labels that each got.

#3196 Removed AppVeyor from bump.sh
  bump.sh
Labels: infrastructure

#3223 Fixed potential torn reads in EventCounters
  src/Npgsql/NpgsqlEventSource.cs
Labels: bug

#3225 Use Interlocked.Read instead of Volatile.Read for PollingCounters
  src/Npgsql/NpgsqlEventSource.cs
Labels: enhancement

#3239 Removed unused mapped enum handler
  src/Npgsql/TypeHandlers/MappedEnumHandler.cs
Labels: refactor

#3271 Fix EnterpriseDB Windows PG installation in CI
  .github/workflows/build.yml
Labels: enhancement, infrastructure
