Repository npgsql/npgsql, pull requests merged in 2020-09, with the labels that each got.

#3114 Fixed pruning of connections and idlecount in ConnectorPool is now kept in sync with correct amount
  src/Npgsql/ConnectorPool.cs
  test/Npgsql.Tests/PoolTests.cs
Labels: bug

#3159 Fixed target frameworks
  test/Directory.Build.props
Labels: bug

#3169 Removed duplicating code
  src/Npgsql/ConnectorPool.cs
Labels: enhancement

#3185 Removed unnecessary try-catches
  src/Npgsql/NpgsqlConnector.cs
Labels: refactor

#3195 Updated GitHub actions
  .github/workflows/build.yml
Labels: infrastructure
