Repository npgsql/npgsql, pull requests merged in 2020-06, with the labels that each got.

#3014 Fix benchmarks for netcoreapp5.0
  Directory.Build.targets
  test/Npgsql.Benchmarks/CommandExecuteBenchmarks.cs
  test/Npgsql.Benchmarks/Commit.cs
  test/Npgsql.Benchmarks/ConnectionCreationBenchmarks.cs
  test/Npgsql.Benchmarks/ConnectionOpenCloseBenchmarks.cs
  test/Npgsql.Benchmarks/GetFieldValue.cs
  test/Npgsql.Benchmarks/TypeHandlers/TypeHandlerBenchmarks.cs
Labels: infrastructure

#3026 Specified line endings for script files
  .gitattributes
Labels: infrastructure

#3039 System.MissingMethodException: 'Constructor on type 'Npgsql.TypeHandlers.CompositeHandlers.CompositeTypeHandlerFactory`1[[...type info...]]' not found.'
  src/Npgsql/TypeMapping/TypeMapperBase.cs
Labels: bug

#2908 VSIX: Integrated security touch-up
  src/VSIX/NpgsqlConnectionUIControl.cs
Labels: enhancement, vsix
