Repository npgsql/npgsql, pull requests merged in 2020-05, with the labels that each got.

#2939 Allow setting runtime configuration parameters in the StartupMessage
  src/Npgsql/NpgsqlConnectionStringBuilder.cs
  src/Npgsql/NpgsqlConnector.cs
  src/Npgsql/PostgresEnvironment.cs
  test/Npgsql.Tests/ConnectionTests.cs
Labels: enhancement

#2947 Get PG long version and detect CockroachDB
  src/Npgsql/PostgresDatabaseInfo.cs
Labels: enhancement

#2950 Support Unix-domain sockets on Windows builds >= 17093
  .github/workflows/build.yml
  src/Npgsql/NpgsqlConnector.cs
  test/Npgsql.Tests/ConnectionTests.cs
Labels: enhancement

#2975 Never use NoSynchronizationContextScope in async methods
  src/Npgsql/NpgsqlDataReader.cs
  src/Npgsql/NpgsqlRawCopyStream.cs
  src/Npgsql/NpgsqlTransaction.cs
Labels: bug

#2982 Optimized and made AOT friendly composite mappings
  src/Npgsql/TypeMapping/INpgsqlTypeMapper.cs
  src/Npgsql/TypeMapping/TypeMapperBase.cs
Labels: performance

#2990 Improve devcontainer for Codespaces
  .devcontainer/db/init-db.sh
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .devcontainer/pgadmin4/config_local.py
  .devcontainer/pgadmin4/servers.json
Labels: infrastructure
