Repository npgsql/npgsql, pull requests merged in 2020-12, with the labels that each got.

#3365 Tsquery handler tests
  test/Npgsql.Tests/Types/FullTextSearchTests.cs
  test/Npgsql.Tests/Types/TsQueryTests.cs
Labels: test

#3424 Fixed socket connection using IPv6 for async method
  src/Npgsql/NpgsqlConnector.cs
Labels: bug

#3427 Fixed PostGIS installation on Windows
  .github/workflows/build.yml
Labels: infrastructure
