Repository npgsql/npgsql, pull requests merged in 2021-02, with the labels that each got.

#3489 Removed invocation of Component's Dispose
  src/Npgsql/NpgsqlCommand.cs
Labels: breaking change, performance

#3551 Remove Task<int> allocation when reading from NetworkStream
  src/Npgsql/Internal/NpgsqlReadBuffer.cs
Labels: performance

#3353 Added rich code navigation to GitHub actions
  .github/workflows/rich-code-nav.yml
Labels: infrastructure
